FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu124
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV PIP_USE_DEPRECATED=legacy-resolver
COPY requirements.api.txt ./
RUN pip install --no-cache-dir -r requirements.api.txt
COPY pyproject.toml ./
COPY src ./src
RUN pip install --no-cache-dir -e .