[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "HybridRAG"
version = "0.1.0"
description = "Hybrid RAG framework"
authors = [{ name = "An Duong" }]
requires-python = ">=3.9"

dependencies = [
  "pydantic==2.10.3",
  "pydantic-settings==2.6.1",
  "python-dotenv==1.0.1",
  "openai==1.59.3",
  "langchain-openai==0.2.14",
  "langchain-core==0.3.28",
  "langchain-community==0.3.13",
  "numpy==1.26.4",
  "faiss-cpu==1.9.0.post1",
  "rank-bm25==0.2.2",
  "sentence-transformers==3.3.1",
  "pyvi==0.1.1",
  "nltk==3.9.2",
  "torch==2.10.0",
  "torchvision==0.25.0",
  "torchaudio==2.10.0",
  "einops",
  "huggingface_hub[hf_xet]",
  "fastapi==0.133.1",
  "uvicorn[standard]==0.32.1",
  "python-multipart==0.0.17",
  "tiktoken==0.8.0",
  "tqdm==4.67.1",
  "requests",
  "cachetools",
  "psycopg2-binary",
  "minio",
  "aioboto3",
  "confluent-kafka",
  "kafka-python",
  "pdfplumber",
  "python-docx",
  "docx2txt"
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-q --strict-markers"
