from .route import Route

MAIN_QUERY_SAMPLES = [
    "Trường Đại học Sư phạm Kỹ thuật Hưng Yên tuyển sinh theo những phương thức nào?",
    "Chỉ tiêu tuyển sinh của trường trong năm nay là bao nhiêu?",
    "Những ngành đào tạo nào đang được tuyển sinh tại trường?",
    "Trường có xét tuyển theo học bạ THPT không?",
    "Có thể xét tuyển vào trường bằng chứng chỉ ngoại ngữ không?",
    "Trường có xét tuyển theo kết quả học tập lớp 10, 11 không?",
    "Ngành nào của trường có tỷ lệ cạnh tranh cao nhất?",
    "Bao giờ trường công bố kết quả trúng tuyển?",
    "Những yếu tố nào ảnh hưởng đến điểm chuẩn các năm?",
    "Sinh viên nghèo có thể vay vốn học tập không?",
    "Bạn có thông tin các giảng viên của trường không?",
    "Giảng viên bộ môn?",
    "Bạn biết thầy quyết và thầy tiến không?",
    "Có ký túc xá riêng cho sinh viên nữ không?",
    "Sinh viên có được hỗ trợ tìm thực tập không?",
    "Cơ sở vật chất của trường như nào?",
    "Chương trình đào tạo của trường có gì đặc biệt?",
    "Trường có chương trình liên kết quốc tế nào không?",
    "Có chương trình đào tạo chất lượng cao không?",
    "Sinh viên có thể tham gia dự án nghiên cứu của giảng viên không?",
    "Có chương trình trao đổi sinh viên với nước ngoài không?",
    "Có thể chuyển ngành sau khi nhập học không?",
    "Có thể bảo lưu kết quả học tập không?",
    "Trường có các câu lạc bộ nào?",
    "Trường có hoạt động ngoại khóa cho sinh viên năm nhất không?",
    "Có khóa học tiếng Việt cho sinh viên quốc tế không?",
    "Học phí cho sinh viên quốc tế có khác gì không?",
    "Quy trình xét tuyển sinh viên quốc tế như thế nào?",
    "Sinh viên có thể tham gia dự án nghiên cứu không?",
    "Trường có hỗ trợ sinh viên tìm việc làm ở nước ngoài không?",
    "Tuyển sinh",
    "Thông tin tuyển sinh",
    "Thông tin cơ sở đầo tạo của trường""Trường có tổ chức ngày hội tư vấn tuyển sinh không?",
    "Thí sinh tự do có được đăng ký xét tuyển vào trường không?",
    "Trường có ưu tiên xét tuyển cho học sinh giỏi tỉnh không?",
    "Điểm chuẩn các ngành của trường trong 3 năm gần đây là bao nhiêu?",
    "Trường có xét tuyển bổ sung sau đợt 1 không?",
    "Hồ sơ xét tuyển vào trường cần chuẩn bị những giấy tờ gì?",
    "Thời gian nhận hồ sơ xét tuyển của trường là khi nào?",
    "Trường có đào tạo hệ vừa học vừa làm không?",
    "Có chương trình đào tạo từ xa hoặc học online không?",
    "Sinh viên năm nhất có bắt buộc ở ký túc xá không?",
    "Ký túc xá của trường có cho sinh viên năm cuối ở không?",
    "Chi phí sinh hoạt trung bình của sinh viên tại trường khoảng bao nhiêu?",
    "Trường có chính sách miễn giảm học phí cho những đối tượng nào?",
    "Sinh viên có thể đóng học phí theo từng học kỳ không?",
    "Trường có học bổng khuyến khích học tập không?",
    "Điều kiện để được xét học bổng của trường là gì?",
    "Trường có các học bổng do doanh nghiệp tài trợ không?",
    "Sinh viên có được làm thêm trong khuôn viên trường không?",
    "Trường có trung tâm hỗ trợ và tư vấn sinh viên không?",
    "Sinh viên năm nhất có thể tham gia nghiên cứu khoa học không?",
    "Quy trình đăng ký đề tài nghiên cứu khoa học sinh viên như thế nào?",
    "Trường có tổ chức hội thảo khoa học cho sinh viên không?",
    "Sinh viên tốt nghiệp có được cấp bảng điểm song ngữ không?",
    "Bằng tốt nghiệp của trường có được công nhận ở nước ngoài không?",
    "Trường có hỗ trợ sinh viên học song bằng không?",
    "Sinh viên có thể học vượt để tốt nghiệp sớm không?",
    "Trường có quy định về cảnh báo học vụ không?",
    "Sinh viên bị cảnh báo học vụ có được tiếp tục học không?",
    "Trường có đào tạo kỹ năng mềm cho sinh viên không?",
    "Các môn học kỹ năng có bắt buộc không?",
    "Trường có liên kết với doanh nghiệp nào để tổ chức thực tập không?",
    "Sinh viên thường được đi thực tập vào năm học nào?",
    "Trường có hỗ trợ giới thiệu việc làm sau khi tốt nghiệp không?",
    "Tỷ lệ sinh viên có việc làm sau khi ra trường là bao nhiêu?",
    "Cựu sinh viên của trường hiện đang làm việc tại những doanh nghiệp nào?",
    "Trường có mạng lưới cựu sinh viên không?",
    "Sinh viên có thể tham gia các cuộc thi học thuật cấp quốc gia không?",
    "Trường có đội tuyển Olympic sinh viên không?",
    "Có thể đăng ký học các học phần giảng dạy bằng tiếng Anh không?",
    "Trường có yêu cầu chuẩn đầu ra ngoại ngữ không?",
    "Chuẩn đầu ra tin học của trường là gì?",
    "Sinh viên quốc tế có được hỗ trợ chỗ ở không?",
    "Trường có bộ phận hỗ trợ riêng cho sinh viên quốc tế không?",
    "Trường có chương trình định hướng cho sinh viên năm nhất không?",
    "Sinh viên có được tham gia các hoạt động đoàn hội không?",
    "Trường có tổ chức các hoạt động tình nguyện cho sinh viên không?",
    "Sinh viên có thể xin giấy xác nhận sinh viên online không?",
    "Thời gian xử lý các thủ tục hành chính cho sinh viên là bao lâu?",
    "Trường có cổng thông tin sinh viên trực tuyến không?",
    "Sinh viên có thể phản hồi chất lượng giảng dạy qua kênh nào?",
    "Trường Đại học Sư phạm Kỹ thuật Hưng Yên được thành lập năm nào?",
    "Trường trực thuộc bộ hoặc cơ quan nào quản lý?",
    "Sứ mệnh và tầm nhìn của nhà trường là gì?",
    "Quy mô đào tạo hiện nay của trường khoảng bao nhiêu sinh viên?",
    "Trường hiện có bao nhiêu khoa và viện đào tạo?",
    "Các khoa đào tạo chính của trường gồm những khoa nào?",
    "Trường có bao nhiêu cơ sở đào tạo?",
    "Địa chỉ chính thức của trường ở đâu?",
    "Khuôn viên trường có diện tích bao nhiêu?",
    "Cơ cấu tổ chức của nhà trường gồm những đơn vị nào?",
    "Ban giám hiệu hiện tại của trường gồm những ai?",
    "Hiệu trưởng hiện nay của trường là ai?",
    "Trường có bao nhiêu giảng viên cơ hữu?",
    "Tỷ lệ giảng viên có trình độ tiến sĩ của trường là bao nhiêu?",
    "Trường có các trung tâm nghiên cứu và chuyển giao công nghệ nào?",
    "Website chính thức của trường là gì?",
    "Trường có các kênh thông tin chính thức nào trên mạng xã hội?",
    "Trường có được kiểm định chất lượng giáo dục không?",
    "Những thành tựu nổi bật của nhà trường trong những năm gần đây là gì?",
    "Định hướng phát triển của trường trong giai đoạn tới là gì?",
    "Ngành công nghệ thông tin có những thông tin gì?"
]

CHITCHAT_SAMPLES = [
    "Bạn là ai?",
    "Xin chào",
    "Chào",
    "Holla",
    "Helo",
    "Bạn có khỏe không?",
    "Bạn có thể giúp tôi không?",
    "Tôi cần giúp đỡ",
    "Bạn có thể kể một câu chuyện cười không?",
    "Bạn có thể kể một câu chuyện không?",
    "Bạn có thể nói chuyện với tôi không?",
    "Tôi cảm thấy buồn",
    "Tôi cảm thấy cô đơn",
    "Tôi cảm thấy stress",
    "Tôi cần lời khuyên",
    "Bạn có thể giúp tôi thư giãn không?",
    "Tôi muốn học một điều mới",
    "Bạn có thể dạy tôi một điều mới không?",
    "Bạn có thể giúp tôi học tiếng Anh không?",
    "Tôi muốn cải thiện kỹ năng giao tiếp",
    "Ê",
    "Ai đẹp trai nhất?",
    "Ai xinh gái nhất?",
    "Tôi rất vui được gặp bạn",
    "Bạn có thể giúp tôi với bài tập về nhà không?",
    "Biết Sơn Tùng không?",
    "Alo",
    "Làm sao để có người yêu?",
    "Tư vấn chuyện tình cảm đi",
    "Ngày hôm nay đẹp nhỉ",
    "Thời tiết hôm nay thế nào?",
    "Có nhạc gì hay không?",
    "Bạn ăn cơm chưa?",
    "Bạn có lời khuyên nào cho tôi về việc học tiếng Anh?",
    "Có sự kiện gì thú vị sắp tới không?",
    "Biết tin gì chưa?",
    "Có thể dạy tôi tiếng Anh không?",
    "Học gì để nhanh giàu đây?",
    "Hi",
    "Có biết Virus là ai không?",
    "Halo",
    "Bạn có biết món ăn nào ngon gần đây không?",
    "Bạn có sở thích nào đặc biệt không?",
    "Bạn có tin vào may mắn không?",
    "Bạn có thể giúp tôi thư giãn một chút được không?",
    "Giúp tôi với",
    "Trường có nhiều gái xinh không?",
    "Cách tán gái hiệu quả?",
    "Cách để đạt điểm cao trong kỳ thi?",
    "Tại sao nước lại trong suốt?",
    "Người nào thông minh nhất lịch sử?",
    "Tại sao con người không thể bay?",
    "Sự khác biệt giữa trà xanh và trà đen?",
    "Làm thế nào để viết một cuốn sách?",
    "Tại sao con người cần ngủ?",
    "Có thể du hành ngược thời gian không?",
    "Bạn có thể giúp tôi tìm hiểu về văn hóa của Nhật Bản không?",
    "Chào buổi sáng",
    "Hôm nay là thứ mấy?",
    "Bạn có thể kể chuyện cười không?",
    "Tôi đang buồn quá",
    "Cảm ơn bạn nhiều",
    "Bye bye",
    "Hẹn gặp lại",
    "Bạn thích màu gì?",
    "Có game nào hay không?",
    "Cuộc sống là gì?",
    "Tại sao trời lại có mây?",
    "Làm sao để giỏi toán?",
    "Cách nấu phở ngon?",
    "Món ăn Việt Nam nào ngon nhất?",
    "Du lịch đâu vui?",
    "Bạn có biết về vũ trụ không?",
    "Làm sao để thành công?",
    "Cách quản lý thời gian hiệu quả?",
    "Tại sao mặt trời mọc ở phía đông?",
    "Có tin đồn gì hay không?",
    "Bạn có thể hát không?",
    "Cách vẽ đẹp?",
    "Học piano có khó không?",
    "Thể thao nào giúp giảm cân nhanh?",
    "Cách chăm sóc da mặt?",
    "Bạn có biết lập trình không?",
    "Python hay Java?",
    "Cách học lập trình hiệu quả?",
    "AI là gì?",
    "Machine learning hoạt động như thế nào?",
    "Blockchain có an toàn không?",
    "Cách bảo mật tài khoản mạng xã hội?",
    "Tại sao iPhone đắt thế?",
    "Điện thoại nào tốt nhất hiện nay?",
    "Cách chọn laptop phù hợp?",
    "Gaming laptop hay laptop văn phòng?",
    "Tai nghe nào chống ồn tốt?",
    "Smartwatch có cần thiết không?",
    "Cách tập gym cho người mới?",
    "Yoga có giúp giảm stress không?",
    "Chạy bộ buổi sáng hay tối tốt hơn?",
    "Bóng đá hay bóng rổ?",
    "World Cup bao giờ diễn ra?",
    "Messi hay Ronaldo?",
    "Cách chơi cờ vua?",
    "Game online nào đang hot?",
    "Netflix có phim gì hay?",
    "Phim Marvel nào hay nhất?",
    "Kpop hay Vpop?",
    "Concert nào đáng xem?",
    "Bạn có thích xem phim kinh dị không?",
    "Sách nào hay để đọc?",
    "Làm sao để tự tin hơn?",
    "Bạn có biết nấu ăn không?",
    "Thức ăn nhanh có hại không?",
    "Cách làm bánh flan ngon?",
    "Du lịch Đà Lạt có gì thú vị?",
    "Bạn có thích nghe nhạc không?",
    "Ca sĩ nào bạn thích?",
    "Làm sao để giao tiếp tốt hơn?",
    "Có cách nào học ngoại ngữ nhanh không?",
    "Bạn có tin vào UFO không?",
    "Cách phối đồ đi chơi?",
    "Bạn có thích cà phê không?",
    "Trà sữa hay cà phê ngon hơn?",
    "Làm sao để chụp ảnh đẹp?",
    "Bạn có biết về nhiếp ảnh không?",
    "Có cách nào giảm cân tự nhiên không?",
    "Thực phẩm nào tốt cho não?",
    "Làm sao để ngủ ngon hơn?",
    "Bạn có biết về thiên văn học không?",
    "Sao Kim có giống Trái Đất không?",
    "Làm sao để làm bạn với người lạ?",
    "Bạn có thích đi biển không?",
    "Đảo Phú Quốc có gì hay?",
    "Cách câu cá hiệu quả?",
    "Bạn có biết chơi guitar không?",
    "Làm sao để học hát hay?",
    "Bạn có tin vào tình yêu đích thực không?",
    "Làm sao để quên một người?",
    "Bạn có biết về yoga không?",
    "Thiền có lợi ích gì?",
    "Cách làm đồ handmade đẹp?",
    "Bạn có thích đi bộ không?",
    "Làm sao để khỏe mạnh hơn?",
    "Bạn có biết về công nghệ 5G không?",
    "AI có thay thế con người không?",
    "Laptop nào phù hợp cho sinh viên?",
    "Cách chọn giày chạy bộ?",
    "Bạn có thích xem hài không?",
    "Clip TikTok nào đang viral?",
    "Làm sao để nổi tiếng trên mạng?",
    "Bạn có biết về tiền điện tử không?",
    "Bitcoin có an toàn không?",
    "Cách đầu tư tiền hiệu quả?",
    "Bạn có thích mùa nào nhất?",
    "Mùa thu có gì đặc biệt?",
    "Làm sao để vượt qua thất bại?",
    "Bạn có thể kể về tuổi thơ không?",
    "Làm sao để làm bạn tốt?",
    "Bạn có biết về ẩm thực thế giới không?",
    "Pizza hay sushi ngon hơn?",
    "Cách làm salad đơn giản?",
    "Bạn có thích đi phượt không?",
    "Làm sao để viết thơ hay?",
    "Chiến tranh thế giới thứ hai là gì?",
    "Cách học sử dễ nhớ?",
    "Bạn có thích xem thời trang không?",
    "Gu thời trang của bạn là gì?",
    "Cách bảo vệ động vật quý hiếm?",
    "Bạn có thích đi leo núi không?",
    "Núi nào đẹp nhất Việt Nam?",
    "Làm sao để đi du lịch tiết kiệm?",
]

MAIN_QUERY_ROUTE = Route(name="main_query", samples=MAIN_QUERY_SAMPLES)
CHITCHAT_ROUTE = Route(name="chitchat", samples=CHITCHAT_SAMPLES)
ROUTES = [MAIN_QUERY_ROUTE, CHITCHAT_ROUTE]
__all__ = ["ROUTES"]